server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

#eureka.client.service-url.defaultZone=http://0.0.0.0:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.jmx.enabled=false

# Enable load balancer
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=product-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/products/**

spring.cloud.gateway.server.webmvc.routes[2].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/inventory/**

spring.cloud.gateway.server.webmvc.routes[3].id=order-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.server.webmvc.routes[4].id=payment-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/payments/**

# Swagger docs routes
spring.cloud.gateway.server.webmvc.routes[5].id=user-service-docs
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/user-service/**
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[6].id=product-service-docs
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/product-service/**
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[7].id=inventory-service-docs
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/inventory-service/**
spring.cloud.gateway.server.webmvc.routes[7].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[8].id=order-service-docs
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/order-service/**
spring.cloud.gateway.server.webmvc.routes[8].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[9].id=payment-service-docs
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/payment-service/**
spring.cloud.gateway.server.webmvc.routes[9].filters[0]=StripPrefix=1

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/user-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Product Service
springdoc.swagger-ui.urls[1].url=/product-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Inventory Service
springdoc.swagger-ui.urls[2].url=/inventory-service/v3/api-docs
springdoc.swagger-ui.urls[3].name=Order Service
springdoc.swagger-ui.urls[3].url=/order-service/v3/api-docs
springdoc.swagger-ui.urls[4].name=Payment Service
springdoc.swagger-ui.urls[4].url=/payment-service/v3/api-docs




