server.port=8082
spring.application.name=product-service

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://smartshop:Smartshop%40123@smartshop-cluster.yxyjjlh.mongodb.net/smartshop_products?retryWrites=true&w=majority&appName=smartshop-cluster

# Eureka
eureka.client.service-url.defaultZone=http://0.0.0.0:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.jmx.enabled=false

springdoc.api-docs.path=/v3/api-docs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher