server.port=8082
spring.application.name=product-service

# MongoDB Atlas
sspring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://smartshop:Smartshop%40123@smartshop-cluster.yxyjjlh.mongodb.net/smartshop_products?retryWrites=true&w=majority&appName=smartshop-cluster}
# Eureka
#eureka.client.service-url.defaultZone=http://0.0.0.0:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

spring.jmx.enabled=false

springdoc.api-docs.path=/v3/api-docs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springdoc.swagger-ui.path=/swagger-ui/index.html